#!/bin/sh
if [ $2 == "frag" ]; then
  cat $1 | tr '\t' '`' | sed 's/`NOP.*/&\n&\n&\n&\n&/' | tr '`' '\t' > $1.tempfghfgh556g
else
  cp $1 $1.tempfghfgh556g
fi

cat $1.tempfghfgh556g |tr '\t' '`' | awk '/^`B/&&(NF==2)&&/ [0-9]/{CNTR[NR]=1+$2;$2="%d"} /^`B/&&(NF>3)&&/^[^,]*, [^,]*, [0-9]/{CNTR[NR]=1+$4;$4="%d,"}{L[NR]=$0}/^`NOP/{for (i in CNTR) {if (CNTR[i]==1){V[i]=D[i]+1;delete CNTR[i]}else D[i]++}}(/^`[A-Z]/)&&($1!="`NOP"){for (i in CNTR) {CNTR[i]--;D[i]++}}END{for (i=1;i<=NR;i++){if(V[i]){printf(L[i],V[i]-1);printf("\n")}else print L[i]}}'| tr '`' '\t' > new$1

rm $1.tempfghfgh556g
