
######################################################################
# Automatically generated by qmake (1.05a) Sat Jan 2 10:47:24 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += qt_test.cpp
